### PR TITLE
Fix #14 support COPY FROM

### LINKED ISSUE #14: COPY table from stdin
Hello.

Could you make it clear - is it possible to perform bulk load of data via COPY table from stdin; statement using go-pgsql? If yes, how?

P.S.: Thank you for this project. You really filled an empty space of pure Go implementation of such important protocol.

### PR DESCRIPTION
**Pull request by temoto**

### CODE REVIEW

**Comment by lxn** [comment]
You are quick :-)

Please add yourself to the AUTHORS file.

Thanks!

**Comment by temoto** [comment]
Done and done.

I just started implementing same for pq and i need to go home to refresh. Clearly out of WTFs today. Your project is like a clean lagoon water in comparison. Now i have even more insights how to make better Go libraries.

**Comment by lxn** [comment]
Thanks :-)

**Comment by temoto** [comment]
Done the execute one. I'm sorry for all those, was not paying enough attention.

**Comment by lxn** [comment]
No worries, thanks for your nice contribution!

**Pull request merged**
